import type { CustomTool, RFEdge, RFNode } from "../types/agent-builder";

type GeneratorSettings = {
  instructions?: string;
  includeChatHistory?: boolean;
  model?: string;
  codeLanguage?: "javascript" | "typescript";
};

type GeneratorOptions = {
  agentId?: string;
  agentName?: string;
  customTools?: CustomTool[];
  settings?: GeneratorSettings;
};

function escapeTemplate(value: string) {
  return value.replace(/`/g, "\\`");
}

function normalizeNode(node: RFNode) {
  return {
    id: node.id,
    label: String(node.data?.label || node.id),
    type: String(node.data?.type || node.type || "default"),
    config: node.data?.config || {},
    position: node.position,
  };
}

export function generateAgentCode(
  nodes: RFNode[],
  edges: RFEdge[],
  agentType = "custom",
  options: GeneratorOptions = {}
): string {
  const agentName = options.agentName || "NOVA Agent";
  const customTools = options.customTools || [];
  const settings = options.settings || {};
  const language = settings.codeLanguage || "javascript";
  const isTs = language === "typescript";
  const serializedNodes = nodes.map(normalizeNode);

  // Collect API keys from nodes
  const apiKeys: Record<string, string> = {};
  nodes.forEach(node => {
    const config = node.data?.config;
    if (config?.apiKeyConfig?.useApiKey && config.apiKeyConfig.apiKey) {
      const key = config.apiKeyConfig.apiKey;
      const type = node.data?.type === 'llm' ? 'openai' : 'api';
      apiKeys[type] = key;
    }
  });

  return `${isTs ? "/* eslint-disable no-console */" : "#!/usr/bin/env node"}
/**
 * Auto-generated by NOVA Agent Builder
 * Agent Name: ${escapeTemplate(agentName)}
 * Agent ID: ${escapeTemplate(options.agentId || "unknown")}
 * Agent Type: ${escapeTemplate(agentType)}
 *
 * Usage:
 * 1. Run: node ${isTs ? "generated-agent.ts" : "generated-agent.js"} "your prompt"
 */

const API_KEYS = ${JSON.stringify(apiKeys, null, 2)};

const AGENT = ${JSON.stringify(
    {
      id: options.agentId || "",
      name: agentName,
      type: agentType,
      settings: {
        instructions: settings.instructions || "",
        includeChatHistory: settings.includeChatHistory ?? true,
        model: settings.model || "gpt-5",
      },
      nodes: serializedNodes,
      edges,
      customTools,
    },
    null,
    2
  )};

${isTs ? "type WorkflowState = Record<string, unknown>;" : ""}

function slugify(value${isTs ? ": string" : ""}) {
  return String(value || "step")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

async function callOpenAI(prompt${isTs ? ": string" : ""}, workflowState${isTs ? ": Record<string, unknown>" : ""}, apiKey${isTs ? "?: string" : ""}) {
  const apiKeyToUse = apiKey || API_KEYS.openai || process.env.OPENAI_API_KEY;

  if (!apiKeyToUse) {
    return {
      mode: "offline",
      content:
        "OPENAI_API_KEY is not set. The workflow still ran, but the model response is in offline mode.",
    };
  }

  const systemPrompt = [
    \`You are \${AGENT.name}.\`,
    AGENT.settings.instructions || "Follow the configured workflow and tools exactly.",
    "Workflow nodes:",
    JSON.stringify(AGENT.nodes, null, 2),
    "Workflow edges:",
    JSON.stringify(AGENT.edges, null, 2),
    "Custom tools:",
    JSON.stringify(AGENT.customTools, null, 2),
    "Current workflow state:",
    JSON.stringify(workflowState, null, 2),
  ].join("\\n\\n");

  const response = await fetch("https://api.openai.com/v1/responses", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: \`Bearer \${apiKeyToUse}\`,
    },
    body: JSON.stringify({
      model: AGENT.settings.model || "gpt-4o-mini",
      messages: [
        {
          role: "system",
          content: [{ type: "input_text", text: systemPrompt }],
        },
        {
          role: "user",
          content: [{ type: "input_text", text: prompt }],
        },
      ],
    },
    }),
  });

  const payload = await response.json();
  if (!response.ok) {
    throw new Error(payload?.error?.message || "OpenAI request failed");
  }

  const fallback =
    payload?.output_text ||
    payload?.output?.map?.((item${isTs ? ": any" : ""}) => item?.content?.map?.((part${isTs ? ": any" : ""}) => part?.text).join("")).join("\\n") ||
    "";

  return {
    mode: "openai",
    content: fallback,
    raw: payload,
  };
}

async function executeHttpTool(tool${isTs ? ": any" : ""}, prompt${isTs ? ": string" : ""}, state${isTs ? ": Record<string, unknown>" : ""}, apiKeyConfig${isTs ? "?: any" : ""}) {
  if (!tool.apiUrl) {
    return {
      ok: false,
      skipped: true,
      reason: "Missing apiUrl",
    };
  }

  const method = (tool.method || "GET").toUpperCase();
  const shouldSendBody = ["POST", "PUT", "PATCH", "DELETE"].includes(method);
  const headers: Record<string, string> = {
    "Content-Type": "application/json",
  };

  // Add API key headers if configured
  const headers${isTs ? ": Record<string, string>" : ""} = {
  "Content-Type": "application/json",
};

// Add API key headers if configured
if (apiKeyConfig?.useApiKey && apiKeyConfig.apiKey) {
  const headerName = 
    apiKeyConfig.headerType === 'custom'
      ? apiKeyConfig.keyName || 'Authorization'
      : apiKeyConfig.headerType === 'api-key'
      ? 'X-API-Key'
      : 'Authorization';

  const headerValue = 
    apiKeyConfig.headerType === 'bearer'
     ? \`Bearer \${apiKeyConfig.apiKey}\`
      : apiKeyConfig.apiKey;

  headers[headerName] = headerValue;
}

  const response = await fetch(tool.apiUrl, {
    method,
    headers,
    body: shouldSendBody
      ? JSON.stringify({
          prompt,
          state,
          params: tool.paramsSchema || {},
        })
      : undefined,
  });

  const contentType = response.headers.get("content-type") || "";
  const data = contentType.includes("application/json")
    ? await response.json()
    : await response.text();

  return {
    ok: response.ok,
    status: response.status,
    data,
  };
}

async function runWorkflow(prompt${isTs ? ": string" : ""})${isTs ? ": Promise<WorkflowState>" : ""} {
  const state${isTs ? ": WorkflowState" : ""} = {
    prompt,
    visitedNodes: [],
  };

  for (const node of AGENT.nodes) {
    const key = slugify(node.label || node.id);
    const type = node.type;
    const config = node.config || {};
    state.visitedNodes.push(node.id);

    if (type === "api") {
      state[key] = await executeHttpTool(
        {
          apiUrl: config.apiUrl,
          method: config.method || "GET",
          paramsSchema: config.paramsSchema || {},
        },
        prompt,
        state,
        config.apiKeyConfig
      );
      continue;
    }

    if (type === "custom") {
      const tool = AGENT.customTools.find((item${isTs ? ": any" : ""}) => item.id === config.toolId);
      state[key] = tool
        ? await executeHttpTool(tool, prompt, state, config.apiKeyConfig)
        : { ok: false, skipped: true, reason: "Custom tool not found" };
      continue;
    }

    if (type === "if") {
      state[key] = {
        branch: config.condition || "manual-condition",
        evaluated: true,
      };
      continue;
    }

    if (type === "while") {
      state[key] = {
        loop: config.condition || "manual-loop",
        maxIterations: config.maxIterations || 3,
      };
      continue;
    }

    if (type === "llm") {
      // Execute an LLM call as part of the workflow step
      const promptForLLM = config.prompt || prompt;
      const llmResp = await callOpenAI(promptForLLM, state, config.apiKeyConfig?.apiKey);
      state[key] = {
        type,
        label: node.label,
        config,
        response: llmResp,
      };
      continue;
    }

    state[key] = {
      type,
      label: node.label,
      config,
    };
  }

  return state;
}

async function runAgent(prompt${isTs ? ": string" : ""}, chatHistory${isTs ? ": Array<{ role: string; content: string }> = []" : " = []"}) {
  const workflow = await runWorkflow(prompt);
  if (AGENT.settings.includeChatHistory) {
    workflow.chatHistory = chatHistory;
  }

  const completion = await callOpenAI(prompt, workflow);
  return {
    agent: AGENT.name,
    mode: completion.mode,
    workflow,
      reply: completion.content,
  };
}

async function main() {
  let prompt = process.argv.slice(2).join(" ").trim();

  if (!prompt) {
    const readline = (await import("readline/promises")).default;
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

    console.log("No prompt provided. Choose an action:");
    console.log("1) Weather lookup");
    console.log("2) Currency conversion");
    console.log("3) Custom prompt");

    const choice = (await rl.question("Select 1, 2 or 3: ")).trim();

    if (choice === "1") {
      const city = (await rl.question("Enter city name (e.g., New York): ")).trim();
      prompt = city ? "Get current weather for " + city : "Get current weather";
    } else if (choice === "2") {
      const from = (await rl.question("From currency (e.g., USD): ")).trim().toUpperCase();
      const to = (await rl.question("To currency (e.g., EUR): ")).trim().toUpperCase();
      const amount = (await rl.question("Amount (e.g., 100): ")).trim();
      prompt = "Convert " + (amount || "1") + " " + (from || "USD") + " to " + (to || "EUR");
    } else if (choice === "3") {
      const custom = (await rl.question("Enter your custom prompt: ")).trim();
      prompt = custom;
    } else {
      console.error("Invalid option selected. Exiting.");
      rl.close();
      process.exit(1);
    }

    rl.close();

    if (!prompt) {
      console.error("No prompt could be generated. Please rerun with parameters or choose a valid option.");
      process.exit(1);
    }
  }

  const result = await runAgent(prompt);
  console.log(
    typeof result.reply === "string"
      ? result.reply
      : JSON.stringify(result.reply, null, 2)
  );
}

if (typeof require !== "undefined" && require.main === module) {
  main().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}

${isTs ? "export { AGENT, runAgent, runWorkflow };" : "module.exports = { AGENT, runAgent, runWorkflow };"}
`;
}
