import type { CustomTool, RFEdge, RFNode } from "../types/agent-builder";

type GeneratorSettings = {
  instructions?: string;
  includeChatHistory?: boolean;
  model?: string;
  codeLanguage?: "javascript" | "typescript";
};

type GeneratorOptions = {
  agentId?: string;
  agentName?: string;
  customTools?: CustomTool[];
  settings?: GeneratorSettings;
};

function escapeTemplate(value: string) {
  return value.replace(/`/g, "\\`");
}

function normalizeNode(node: RFNode) {
  return {
    id: node.id,
    label: String(node.data?.label || node.id),
    type: String(node.data?.type || node.type || "default"),
    config: node.data?.config || {},
    position: node.position,
  };
}

export function generateAgentCode(
  nodes: RFNode[],
  edges: RFEdge[],
  agentType = "custom",
  options: GeneratorOptions = {}
): string {
  const agentName = options.agentName || "NOVA Agent";
  const customTools = options.customTools || [];
  const settings = options.settings || {};
  const language = settings.codeLanguage || "javascript";
  const isTs = language === "typescript";
  const serializedNodes = nodes.map(normalizeNode);

  const apiKeys: Record<string, string> = {};
  nodes.forEach((node) => {
    const config = node.data?.config;
    if (config?.apiKeyConfig?.useApiKey && config.apiKeyConfig.apiKey) {
      const key = config.apiKeyConfig.apiKey;
      const type = node.data?.type === "llm" ? "openai" : "api";
      apiKeys[type] = key;
    }
  });

  const generatedToolNodes = serializedNodes
    .filter((node) => node.type === "api" || node.type === "custom")
    .map((node) => ({
      id: node.id,
      name: node.label,
      description: node.type === "custom" ? "Custom tool from NOVA builder" : "API node from NOVA builder",
      apiUrl: node.config?.apiUrl || "",
      method: node.config?.method || "GET",
      paramsSchema: node.config?.paramsSchema || {},
      apiKey:
        node.config?.apiKey ||
        node.config?.apiKeyConfig?.apiKey ||
        undefined,
    }));

  return `${isTs ? "/* eslint-disable no-console */" : "/* eslint-disable no-console */"}
/**
 * Auto-generated by NOVA Agent Builder
 * Agent Name: ${escapeTemplate(agentName)}
 * Agent ID: ${escapeTemplate(options.agentId || "unknown")}
 * Agent Type: ${escapeTemplate(agentType)}
 *
 * Usage:
 * 1. Save this file as ${isTs ? "generated-agent.ts" : "generated-agent.js"}
 * 2. Run it in a terminal with: node ${isTs ? "generated-agent.ts" : "generated-agent.js"}
 * 3. Chat in the terminal with commands like:
 *    joke 1
 *    weather mumbai
 *    currency 300 INR USD
 *    time Asia/Kolkata
 *    country india
 *    crypto bitcoin usd,inr
 *    ip 8.8.8.8
 *    number 300
 */

const API_KEYS = ${JSON.stringify(apiKeys, null, 2)};
const BASE_URL = process.env.NOVA_AGENT_BASE_URL || process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";

const AGENT = ${JSON.stringify(
    {
      id: options.agentId || "",
      name: agentName,
      type: agentType,
      settings: {
        instructions: settings.instructions || "",
        includeChatHistory: settings.includeChatHistory ?? true,
        model: settings.model || "gpt-5-mini",
      },
      nodes: serializedNodes,
      edges,
      customTools,
      generatedToolNodes,
    },
    null,
    2
  )};

${isTs ? "type WorkflowState = Record<string, unknown>;\ntype ChatMessage = { role: string; content: string };\ntype RuntimeTool = { id: string; name: string; description?: string; apiUrl?: string; method?: string; paramsSchema?: Record<string, unknown>; apiKey?: string; source: string };\ntype ToolKind = \"currency\" | \"time\" | \"weather\" | \"country\" | \"crypto\" | \"ip\" | \"joke\" | \"number\" | \"generic\";\n" : ""}
const TOOL_KIND_ALIASES = {
  currency: ["currency", "convert", "rates", "fx", "exchange"],
  time: ["time", "timezone", "clock"],
  weather: ["weather", "forecast", "temperature"],
  country: ["country", "nation", "capital"],
  crypto: ["crypto", "coin", "bitcoin", "ethereum", "dogecoin", "solana"],
  ip: ["ip", "location", "geoip"],
  joke: ["joke", "funny", "laugh"],
  number: ["number", "fact", "math", "datefact"],
  generic: ["tool"],
};

function slugify(value${isTs ? ": string" : ""}) {
  return String(value || "tool")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function resolveUrl(url${isTs ? ": string" : ""}) {
  if (!url) return url;
  if (/^https?:\\/\\//i.test(url)) {
    return url;
  }
  return new URL(url.startsWith("/") ? url : \`/\${url}\`, BASE_URL).toString();
}

function normalizeText(value${isTs ? ": unknown" : ""}) {
  return String(value || "").trim();
}

function normalizeWords(value${isTs ? ": string" : ""}) {
  return normalizeText(value)
    .toLowerCase()
    .split(/[^a-z0-9/_.:-]+/)
    .filter(Boolean);
}

function escapeRegExp(value${isTs ? ": string" : ""}) {
  return String(value).replace(/[.*+?^\\$\\{\\}()|[\\]\\\\]/g, "\\\\$&");
}

function pickToolKind(tool${isTs ? ": RuntimeTool" : ""})${isTs ? ": ToolKind" : ""} {
  const haystack = [tool.name, tool.description, tool.id, tool.apiUrl].join(" ").toLowerCase();
  if (/exchangerate|currency|open-er-api|fx/.test(haystack)) return "currency";
  if (/worldtimeapi|timezone|current time/.test(haystack)) return "time";
  if (/weather|openweathermap|open-meteo/.test(haystack)) return "weather";
  if (/restcountries|country/.test(haystack)) return "country";
  if (/coingecko|crypto|bitcoin|ethereum|dogecoin|solana/.test(haystack)) return "crypto";
  if (/ipapi|geoip|ip address|ip location/.test(haystack)) return "ip";
  if (/joke/.test(haystack)) return "joke";
  if (/numbersapi|number fact|fun fact/.test(haystack)) return "number";
  return "generic";
}

function getToolAliases(tool${isTs ? ": RuntimeTool" : ""}, kind${isTs ? ": ToolKind" : ""}) {
  const set = new Set([
    ...normalizeWords(tool.name),
    ...normalizeWords(tool.id),
    ...normalizeWords(tool.description || ""),
    ...(TOOL_KIND_ALIASES[kind] || []),
  ]);

  if (kind === "joke") set.add("jokes");
  if (kind === "number") set.add("numbers");
  if (kind === "country") set.add("countries");

  return Array.from(set);
}

function getRuntimeTools()${isTs ? ": RuntimeTool[]" : ""} {
  const merged = [...(AGENT.customTools || []), ...(AGENT.generatedToolNodes || [])];
  const seen = new Set();
  const runtimeTools = [];

  for (const item of merged) {
    const apiUrl = normalizeText(item.apiUrl);
    if (!apiUrl) continue;

    const key = [item.id, item.name, apiUrl, item.method || "GET"].join("|");
    if (seen.has(key)) continue;
    seen.add(key);

    runtimeTools.push({
      id: item.id || slugify(item.name || apiUrl),
      name: item.name || item.id || "API Tool",
      description: item.description || "",
      apiUrl,
      method: (item.method || "GET").toUpperCase(),
      paramsSchema: item.paramsSchema || {},
      apiKey: item.apiKey,
      source: (AGENT.customTools || []).some((tool) => tool.id === item.id) ? "custom-tool" : "node",
    });
  }

  return runtimeTools;
}

const RUNTIME_TOOLS = getRuntimeTools();
const SINGLE_TOOL = RUNTIME_TOOLS.length === 1 ? RUNTIME_TOOLS[0] : null;

function getPreferredAlias(kind${isTs ? ": ToolKind" : ""}) {
  return (TOOL_KIND_ALIASES[kind] || [kind || "api"])[0] || "api";
}

function getDefaultExamples(kind${isTs ? ": ToolKind" : ""}) {
  if (kind === "currency") return ["INR", "USD", "EUR", "300 INR USD"];
  if (kind === "time") return ["Asia/Kolkata", "America/New_York", "Europe/London"];
  if (kind === "weather") return ["Mumbai", "Delhi", "Paris, France"];
  if (kind === "country") return ["India", "Japan", "United States"];
  if (kind === "crypto") return ["bitcoin", "ethereum", "dogecoin"];
  if (kind === "ip") return ["8.8.8.8", "1.1.1.1"];
  if (kind === "joke") return ["joke", "joke 1"];
  if (kind === "number") return ["300", "42"];
  return ["api"];
}

function findToolMatch(input${isTs ? ": string" : ""}) {
  if (SINGLE_TOOL) {
    const kind = pickToolKind(SINGLE_TOOL);
    return {
      tool: SINGLE_TOOL,
      kind,
      aliases: getToolAliases(SINGLE_TOOL, kind),
      score: 999,
    };
  }

  const text = normalizeText(input).toLowerCase();
  const firstWord = normalizeWords(text)[0] || "";

  const ranked = RUNTIME_TOOLS.map((tool) => {
    const kind = pickToolKind(tool);
    const aliases = getToolAliases(tool, kind);
    const score = aliases.reduce((total, alias) => {
      if (text === alias) return total + 6;
      if (firstWord === alias) return total + 5;
      if (text.includes(alias)) return total + 2;
      return total;
    }, 0);

    return { tool, kind, aliases, score };
  })
    .filter((item) => item.score > 0)
    .sort((a, b) => b.score - a.score);

  if (ranked[0]) {
    return ranked[0];
  }

  if (isLikelyCurrencyPrompt(input)) {
    const currencyTool = RUNTIME_TOOLS
      .map((tool) => {
        const kind = pickToolKind(tool);
        return { tool, kind, aliases: getToolAliases(tool, kind), score: 1 };
      })
      .find((item) => item.kind === "currency");

    if (currencyTool) {
      return currencyTool;
    }
  }

  return null;
}

function removeLeadingAlias(input${isTs ? ": string" : ""}, aliases${isTs ? ": string[]" : ""}) {
  let output = normalizeText(input);
  for (const alias of aliases) {
    const pattern = new RegExp(\`^\\\\s*\${escapeRegExp(alias)}\\\\b[:\\s-]*\`, "i");
    if (pattern.test(output)) {
      output = output.replace(pattern, "");
      break;
    }
  }
  return output.trim();
}

function extractNumber(value${isTs ? ": string" : ""}) {
  const match = value.match(/-?\\d+(?:\\.\\d+)?/);
  return match ? Number(match[0]) : null;
}

function extractCurrencyCode(value${isTs ? ": string" : ""}) {
  const trimmed = normalizeText(value).toUpperCase();
  if (/^[A-Z]{3}$/.test(trimmed)) {
    return trimmed;
  }
  return trimmed.match(/\\b[A-Z]{3}\\b/)?.[0] || null;
}

function isLikelyCurrencyPrompt(value${isTs ? ": string" : ""}) {
  const normalized = normalizeText(value);
  return Boolean(extractCurrencyCode(normalized)) || /\\bcurrency\\b|\\bconvert\\b|\\brate\\b|\\bexchange\\b/i.test(normalized);
}

function normalizeCurrencyApiUrl(url${isTs ? ": string" : ""}, input${isTs ? ": string" : ""}) {
  const configuredCode = url.match(/\\/([A-Z]{3})\\/?$/i)?.[1]?.toUpperCase() || null;
  const desiredCode = extractCurrencyCode(input) || configuredCode || "INR";

  if (/\\/api\\/currency-converter/i.test(url)) {
    return {
      mode: "converter",
      url,
      base: desiredCode,
    };
  }

  if (/api\\.exchangerate-api\\.com\\/v4\\/latest/i.test(url) || /open\\.er-api\\.com\\/v1\\/latest/i.test(url)) {
    const cleanedUrl = url.replace(/\\/([A-Z]{3})\\/?$/i, "");
    return {
      mode: "rates",
      url: cleanedUrl.replace(/\\/$/, "") + "/" + encodeURIComponent(desiredCode),
      base: desiredCode,
    };
  }

  return {
    mode: "rates",
    url,
    base: desiredCode,
  };
}

function parseCurrencyPrompt(input${isTs ? ": string" : ""}) {
  const cleaned = input.replace(/,/g, " ").replace(/\\s+/g, " ").trim();
  const codeMatches = cleaned.toUpperCase().match(/\\b[A-Z]{3}\\b/g) || [];
  const amountMatch = cleaned.match(/\\d+(?:\\.\\d+)?/);

  if (codeMatches.length >= 2) {
    return {
      amount: Number(amountMatch?.[0] || 1),
      from: codeMatches[0],
      to: codeMatches[1],
    };
  }

  if (codeMatches.length === 1) {
    return {
      amount: Number(amountMatch?.[0] || 1),
      from: codeMatches[0],
      to: null,
    };
  }

  return {
    amount: Number(amountMatch?.[0] || 1),
    from: "INR",
    to: "USD",
  };
}

function parseWeatherPrompt(input${isTs ? ": string" : ""}, aliases${isTs ? ": string[]" : ""}) {
  return removeLeadingAlias(input, aliases) || "Mumbai";
}

function parseCountryPrompt(input${isTs ? ": string" : ""}, aliases${isTs ? ": string[]" : ""}) {
  return removeLeadingAlias(input, aliases) || "india";
}

function parseTimezonePrompt(input${isTs ? ": string" : ""}, aliases${isTs ? ": string[]" : ""}) {
  const value = removeLeadingAlias(input, aliases) || "Asia/Kolkata";
  return value.replace(/\\s+/g, "_");
}

function parseCryptoPrompt(input${isTs ? ": string" : ""}, aliases${isTs ? ": string[]" : ""}) {
  const remainder = removeLeadingAlias(input, aliases);
  const parts = remainder.split(/\\s+/).filter(Boolean);
  return {
    id: (parts[0] || "bitcoin").toLowerCase(),
    vsCurrencies: (parts[1] || "usd,inr").toLowerCase(),
  };
}

function parseIpPrompt(input${isTs ? ": string" : ""}, aliases${isTs ? ": string[]" : ""}) {
  const value = removeLeadingAlias(input, aliases) || "me";
  return value.toLowerCase() === "me" ? "json" : \`\${value}/json\`;
}

function parseJokePrompt(input${isTs ? ": string" : ""}) {
  const count = Math.max(1, Math.min(5, Math.floor(extractNumber(input) || 1)));
  return count;
}

function parseNumberPrompt(input${isTs ? ": string" : ""}, aliases${isTs ? ": string[]" : ""}) {
  const remainder = removeLeadingAlias(input, aliases);
  const dateMatch = remainder.match(/(\\d{1,2})[\\/-](\\d{1,2})/);
  if (dateMatch) {
    return { kind: "date", value: \`\${dateMatch[1]}/\${dateMatch[2]}/date\` };
  }

  const number = extractNumber(remainder);
  return { kind: "number", value: String(number ?? 300) };
}

function buildToolRequest(tool${isTs ? ": RuntimeTool" : ""}, kind${isTs ? ": ToolKind" : ""}, input${isTs ? ": string" : ""}, aliases${isTs ? ": string[]" : ""}) {
  const method = (tool.method || "GET").toUpperCase();
  const directUrl = resolveUrl(tool.apiUrl || "");

  if (kind === "currency") {
    const parsed = parseCurrencyPrompt(input);
    const normalizedTarget = normalizeCurrencyApiUrl(directUrl, input);

    if (normalizedTarget.mode === "converter") {
      return {
        method: "POST",
        url: normalizedTarget.url,
        body: { amount: parsed.amount, from: parsed.from, to: parsed.to || "USD" },
      };
    }

    return {
      method: "GET",
      url: normalizedTarget.url,
      meta: {
        ...parsed,
        from: normalizedTarget.base,
      },
    };
  }

  if (kind === "time") {
    const timezone = parseTimezonePrompt(input, aliases);
    if (/\\/api\\/timezone-info/i.test(directUrl)) {
      return {
        method: "POST",
        url: directUrl,
        body: { timezone },
      };
    }
    return {
      method: "GET",
      url: directUrl.replace(/\\/$/, "") + "/" + timezone,
      meta: { timezone },
    };
  }

  if (kind === "weather") {
    const city = parseWeatherPrompt(input, aliases);
    if (/\\/api\\/weather/i.test(directUrl)) {
      return {
        method: "POST",
        url: directUrl,
        body: { city, provider: /openweathermap/i.test(tool.apiUrl || "") ? "openweathermap" : "open-meteo", apiKey: tool.apiKey || API_KEYS.api || process.env.OPENWEATHER_API_KEY },
      };
    }

    const separator = directUrl.includes("?") ? "&" : "?";
    const apiKey = tool.apiKey || API_KEYS.api || process.env.OPENWEATHER_API_KEY || "";
    return {
      method: "GET",
      url: \`\${directUrl}\${separator}q=\${encodeURIComponent(city)}&appid=\${encodeURIComponent(apiKey)}&units=metric\`,
      meta: { city },
    };
  }

  if (kind === "country") {
    const country = parseCountryPrompt(input, aliases);
    if (/\\/api\\/country-info/i.test(directUrl)) {
      return {
        method: "POST",
        url: directUrl,
        body: { country },
      };
    }
    return {
      method: "GET",
      url: directUrl.replace(/\\/$/, "") + "/" + encodeURIComponent(country),
      meta: { country },
    };
  }

  if (kind === "crypto") {
    const parsed = parseCryptoPrompt(input, aliases);
    if (/\\/api\\/crypto-price/i.test(directUrl)) {
      return {
        method: "POST",
        url: directUrl,
        body: { coin: parsed.id, currencies: parsed.vsCurrencies },
      };
    }

    const targetUrl = new URL(directUrl);
    targetUrl.searchParams.set("ids", parsed.id);
    targetUrl.searchParams.set("vs_currencies", parsed.vsCurrencies);
    return {
      method: "GET",
      url: targetUrl.toString(),
      meta: parsed,
    };
  }

  if (kind === "ip") {
    const path = parseIpPrompt(input, aliases);
    if (/\\/api\\/ip-location/i.test(directUrl)) {
      return {
        method: "POST",
        url: directUrl,
        body: { ip: path === "json" ? "" : path.replace(/\\/json$/, "") },
      };
    }
    return {
      method: "GET",
      url: directUrl.replace(/\\/$/, "") + "/" + path,
      meta: { path },
    };
  }

  if (kind === "joke") {
    return {
      method: "GET",
      url: directUrl,
      repeat: parseJokePrompt(input),
    };
  }

  if (kind === "number") {
    const parsed = parseNumberPrompt(input, aliases);
    if (/\\/api\\/number-fact/i.test(directUrl)) {
      return {
        method: "POST",
        url: directUrl,
        body: parsed.kind === "date" ? { input: parsed.value } : { number: parsed.value },
      };
    }
    return {
      method: "GET",
      url: directUrl.replace(/\\/$/, "") + "/" + parsed.value,
      meta: parsed,
    };
  }

  return {
    method,
    url: directUrl,
    body: method === "GET" ? undefined : { prompt: input, params: tool.paramsSchema || {} },
  };
}

async function executeRequest(request${isTs ? ": { method: string; url: string; body?: Record<string, unknown>; repeat?: number; meta?: Record<string, unknown> }" : ""}, tool${isTs ? ": RuntimeTool" : ""}) {
  const repeat = Math.max(1, Math.min(5, request.repeat || 1));
  const responses = [];

  for (let index = 0; index < repeat; index += 1) {
    const headers${isTs ? ": Record<string, string>" : ""} = {
      Accept: "application/json, text/plain;q=0.9, */*;q=0.8",
    };

    if (request.body) {
      headers["Content-Type"] = "application/json";
    }

    if (tool.apiKey && !headers.Authorization) {
      headers.Authorization = \`Bearer \${tool.apiKey}\`;
    }

    const response = await fetch(request.url, {
      method: request.method,
      headers,
      body: request.body ? JSON.stringify(request.body) : undefined,
    });

    const contentType = response.headers.get("content-type") || "";
    const data = contentType.includes("application/json")
      ? await response.json()
      : await response.text();

    if (!response.ok) {
      const message =
        typeof data === "string"
          ? data
          : data?.error || data?.message || JSON.stringify(data);
      throw new Error(message || \`Request failed with status \${response.status}\`);
    }

    responses.push(data);
  }

  return {
    toolId: tool.id,
    toolName: tool.name,
    request,
    data: repeat === 1 ? responses[0] : responses,
  };
}

function formatToolResult(kind${isTs ? ": ToolKind" : ""}, result${isTs ? ": any" : ""}) {
  const data = result.data;

  if (kind === "joke") {
    const jokes = Array.isArray(data) ? data : [data];
    return jokes
      .map((item, index) => {
        const setup = item?.setup || item?.question || item?.text || JSON.stringify(item);
        const punchline = item?.punchline ? "\\n" + item.punchline : "";
        return \`\${index + 1}. \${setup}\${punchline}\`;
      })
      .join("\\n\\n");
  }

  if (kind === "number") {
    return data?.text || data?.fact || String(data);
  }

  if (kind === "time") {
    return [
      \`Timezone: \${data?.timezone || result.request.meta?.timezone || "unknown"}\`,
      \`Datetime: \${data?.datetime || data?.currentDateTime || data?.utc_datetime || "unknown"}\`,
      \`UTC Offset: \${data?.utc_offset || data?.utcOffset || "unknown"}\`,
    ].join("\\n");
  }

  if (kind === "weather") {
    return [
      \`Weather for \${data?.city || result.request.body?.city || "unknown"}\${data?.country ? ", " + data.country : ""}\`,
      \`Temperature: \${data?.temperature ?? data?.main?.temp ?? "unknown"}\${typeof (data?.temperature ?? data?.main?.temp) === "number" ? " C" : ""}\`,
      \`Feels like: \${data?.feelsLike ?? data?.main?.feels_like ?? "unknown"}\${typeof (data?.feelsLike ?? data?.main?.feels_like) === "number" ? " C" : ""}\`,
      \`Condition: \${data?.description || data?.weather?.[0]?.description || "unknown"}\`,
      \`Humidity: \${data?.humidity ?? data?.main?.humidity ?? "unknown"}\`,
      \`Wind: \${data?.windSpeed ?? data?.wind?.speed ?? "unknown"}\`,
    ].join("\\n");
  }

  if (kind === "currency") {
    if (typeof data?.convertedAmount === "number") {
      return \`\${data.amount} \${data.from} = \${data.convertedAmount} \${data.to} (rate: \${data.rate})\`;
    }

    const meta = result.request.meta || {};
    const rate = data?.rates?.[meta.to || "USD"];
    if (typeof rate === "number") {
      const amount = Number(meta.amount || 1);
      const target = meta.to || "USD";
      return \`\${amount} \${meta.from} = \${(amount * rate).toFixed(2)} \${target} (live rate: \${rate})\`;
    }

    return JSON.stringify(data, null, 2);
  }

  if (kind === "country") {
    const country = Array.isArray(data) ? data[0] : data;
    const currency = country?.currencies
      ? Object.entries(country.currencies)
          .map(([code, info]) => \`\${code} (\${info?.name || "unknown"})\`)
          .join(", ")
      : "unknown";
    const languages = country?.languages
      ? Object.values(country.languages).join(", ")
      : "unknown";
    return [
      \`Country: \${country?.name?.common || country?.name || "unknown"}\`,
      \`Capital: \${Array.isArray(country?.capital) ? country.capital.join(", ") : country?.capital || "unknown"}\`,
      \`Population: \${country?.population?.toLocaleString?.() || country?.population || "unknown"}\`,
      \`Currencies: \${currency}\`,
      \`Languages: \${languages}\`,
      \`Flag: \${country?.flag || country?.flags?.emoji || "unknown"}\`,
    ].join("\\n");
  }

  if (kind === "crypto") {
    const [coin, prices] = Object.entries(data || {})[0] || ["unknown", {}];
    const formatted = Object.entries(prices || {})
      .map(([currency, price]) => \`\${currency.toUpperCase()}: \${price}\`)
      .join("\\n");
    return \`Crypto: \${coin}\\n\${formatted || JSON.stringify(data, null, 2)}\`;
  }

  if (kind === "ip") {
    return [
      \`IP: \${data?.ip || "unknown"}\`,
      \`City: \${data?.city || "unknown"}\`,
      \`Region: \${data?.region || data?.region_code || "unknown"}\`,
      \`Country: \${data?.country_name || data?.country || "unknown"}\`,
      \`Org: \${data?.org || "unknown"}\`,
      \`Coordinates: \${data?.latitude ?? "unknown"}, \${data?.longitude ?? "unknown"}\`,
    ].join("\\n");
  }

  if (typeof data === "string") {
    return data;
  }

  if (data?.text) {
    return data.text;
  }

  return JSON.stringify(data, null, 2);
}

function buildHelpText() {
  if (SINGLE_TOOL) {
    const kind = pickToolKind(SINGLE_TOOL);
    const examples = getDefaultExamples(kind);
    return [
      \`\${SINGLE_TOOL.name} Terminal Chat\`,
      \`Connected API: \${SINGLE_TOOL.apiUrl}\`,
      \`Type directly in terminal. Every message will use this \${kind} API.\`,
      "",
      "Examples:",
      ...examples,
      "",
      "Type 'exit' to quit.",
    ].join("\\n");
  }

  const commandLines = RUNTIME_TOOLS.map((tool) => {
    const kind = pickToolKind(tool);
    const alias = getPreferredAlias(kind);
    return \`- \${alias}: \${tool.name} -> \${tool.apiUrl}\`;
  });

  return [
    \`NOVA Terminal Chat\`,
    "Type a message directly and the matching API agent will answer here.",
    "Available commands:",
    ...commandLines,
    "",
    "Examples:",
    "joke 1",
    "weather mumbai",
    "currency 300 INR USD",
    "time Asia/Kolkata",
    "country india",
    "crypto bitcoin usd,inr",
    "ip 8.8.8.8",
    "number 300",
    "",
    "Type 'help' to see commands or 'exit' to quit.",
  ].join("\\n");
}

function getActiveAgentName(workflowState${isTs ? ": Record<string, unknown>" : ""}) {
  const matchedTool = workflowState?.toolMatch;
  if (matchedTool && typeof matchedTool === "object" && matchedTool.toolName) {
    return \`\${matchedTool.toolName}\`;
  }
  return AGENT.name;
}

async function callOpenAI(prompt${isTs ? ": string" : ""}, workflowState${isTs ? ": Record<string, unknown>" : ""}, apiKey${isTs ? "?: string" : ""}) {
  const apiKeyToUse = apiKey || API_KEYS.openai || process.env.OPENAI_API_KEY;

  if (!apiKeyToUse) {
    return {
      mode: "offline",
      content: buildHelpText(),
    };
  }

  const systemPrompt = [
    \`You are \${AGENT.name}.\`,
    AGENT.settings.instructions || "Help the user and use the available runtime tools when possible.",
    "Available tools:",
    JSON.stringify(
      RUNTIME_TOOLS.map((tool) => ({
        id: tool.id,
        name: tool.name,
        description: tool.description,
        apiUrl: tool.apiUrl,
        kind: pickToolKind(tool),
      })),
      null,
      2
    ),
    "Workflow state:",
    JSON.stringify(workflowState, null, 2),
  ].join("\\n\\n");

  const response = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: \`Bearer \${apiKeyToUse}\`,
    },
    body: JSON.stringify({
      model: AGENT.settings.model || "gpt-5-mini",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: prompt },
      ],
      temperature: 0.4,
    }),
  });

  const payload = await response.json();
  if (!response.ok) {
    throw new Error(payload?.error?.message || "OpenAI request failed");
  }

  return {
    mode: "openai",
    content: payload?.choices?.[0]?.message?.content || "",
    raw: payload,
  };
}

async function runWorkflow(prompt${isTs ? ": string" : ""})${isTs ? ": Promise<WorkflowState>" : ""} {
  const state${isTs ? ": WorkflowState" : ""} = {
    prompt,
    visitedNodes: AGENT.nodes.map((node${isTs ? ": any" : ""}) => node.id),
    availableTools: RUNTIME_TOOLS.map((tool) => ({
      id: tool.id,
      name: tool.name,
      kind: pickToolKind(tool),
      apiUrl: tool.apiUrl,
    })),
  };

  const match = findToolMatch(prompt);
  if (!match) {
    state.toolMatch = null;
    return state;
  }

  const request = buildToolRequest(match.tool, match.kind, prompt, match.aliases);
  const result = await executeRequest(request, match.tool);
  state.toolMatch = {
    toolId: match.tool.id,
    toolName: match.tool.name,
    kind: match.kind,
    aliases: match.aliases,
  };
  state.toolResult = result;
  state.reply = formatToolResult(match.kind, result);
  return state;
}

async function runAgent(prompt${isTs ? ": string" : ""}, chatHistory${isTs ? ": ChatMessage[] = []" : " = []"}) {
  const workflow = await runWorkflow(prompt);
  if (AGENT.settings.includeChatHistory) {
    workflow.chatHistory = chatHistory;
  }

  if (typeof workflow.reply === "string" && workflow.reply.trim()) {
    return {
      agent: getActiveAgentName(workflow),
      mode: "tool",
      workflow,
      reply: workflow.reply,
    };
  }

  const completion = await callOpenAI(prompt, workflow);
  return {
    agent: getActiveAgentName(workflow),
    mode: completion.mode,
    workflow,
    reply: completion.content || buildHelpText(),
  };
}

async function main() {
  let prompt = process.argv.slice(2).join(" ").trim();

  if (!prompt) {
    if (!process.stdin.isTTY) {
      console.log(buildHelpText());
      console.log("");
      console.log("Interactive chat needs a real terminal.");
      console.log("In VS Code, enable Code Runner setting: Run In Terminal.");
      return;
    }

    const readline = (await import("readline/promises")).default;
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    const chatHistory${isTs ? ": ChatMessage[]" : ""} = [];

    console.log(buildHelpText());
    console.log("");

    while (true) {
      const userInput = (await rl.question("> ")).trim();
      if (!userInput) continue;
      if (["exit", "quit"].includes(userInput.toLowerCase())) break;
      if (userInput.toLowerCase() === "help") {
        console.log("\\n" + buildHelpText() + "\\n");
        continue;
      }

      chatHistory.push({ role: "user", content: userInput });
      const result = await runAgent(userInput, chatHistory);
      const reply =
        typeof result.reply === "string"
          ? result.reply
          : JSON.stringify(result.reply, null, 2);

      const renderedReply = \`[\${result.agent}]\\n\${reply}\`;
      console.log("\\n" + renderedReply + "\\n");
      chatHistory.push({ role: "assistant", content: renderedReply });
    }

    rl.close();
    return;
  }

  const result = await runAgent(prompt);
  console.log(
    typeof result.reply === "string"
      ? \`[\${result.agent}]\\n\${result.reply}\`
      : \`[\${result.agent}]\\n\${JSON.stringify(result.reply, null, 2)}\`
  );
}

if (typeof require !== "undefined" && require.main === module) {
  main().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}

${isTs ? "export { AGENT, runAgent, runWorkflow };" : "module.exports = { AGENT, runAgent, runWorkflow };"}
`;
}
