import type { CustomTool, RFEdge, RFNode } from "../types/agent-builder";

type CodeLanguage = "javascript" | "typescript" | "python";

type GeneratorSettings = {
  instructions?: string;
  includeChatHistory?: boolean;
  model?: string;
  outputFormat?: "text" | "json";
  codeLanguage?: CodeLanguage;
};

type GeneratorOptions = {
  agentId?: string;
  agentName?: string;
  customTools?: CustomTool[];
  settings?: GeneratorSettings;
};

type NormalizedNode = {
  id: string;
  label: string;
  type: string;
  config: Record<string, unknown>;
  position: { x: number; y: number };
};

type ApiKeyConfig = NonNullable<CustomTool["apiKeyConfig"]>;

function escapeTemplate(value: string) {
  return String(value || "")
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

function escapePythonBlock(value: string) {
  return String(value || "").replace(/'''/g, "\\'\\'\\'");
}

function normalizeNode(node: RFNode): NormalizedNode {
  return {
    id: node.id,
    label: String(node.data?.label || node.id),
    type: String(node.data?.type || node.type || "default"),
    config: (node.data?.config || {}) as Record<string, unknown>,
    position: node.position,
  };
}

function normalizeApiKeyConfig(config: unknown): ApiKeyConfig | undefined {
  if (!config || typeof config !== "object") return undefined;
  const value = config as Record<string, unknown>;
  const authType = value.authType || value.headerType;

  if (typeof value.useApiKey !== "boolean" || typeof value.apiKey !== "string") {
    return undefined;
  }

  return {
    useApiKey: value.useApiKey,
    apiKey: value.apiKey,
    authType:
      authType === "api-key" ||
      authType === "query" ||
      authType === "custom" ||
      authType === "bearer"
        ? authType
        : "bearer",
    customHeaderName:
      typeof value.customHeaderName === "string"
        ? value.customHeaderName
        : typeof value.keyName === "string"
          ? value.keyName
          : undefined,
  };
}

function buildGeneratedToolNodes(nodes: NormalizedNode[]) {
  return nodes
    .filter((node) => node.type === "api" || node.type === "custom")
    .map((node) => {
      const config = node.config || {};
      const nestedApiKey =
        typeof config.apiKeyConfig === "object" &&
        config.apiKeyConfig &&
        "apiKey" in (config.apiKeyConfig as Record<string, unknown>)
          ? String((config.apiKeyConfig as Record<string, unknown>).apiKey || "")
          : "";

      return {
        id: node.id,
        name: String(config.apiCallName || node.label || node.id),
        description:
          node.type === "custom"
            ? "Custom tool from NOVA builder"
            : "API node from NOVA builder",
        apiUrl: String(config.apiUrl || ""),
        method: String(config.method || "GET").toUpperCase(),
        paramsSchema: config.paramsSchema || {},
        apiKey: String(config.apiKey || nestedApiKey || "").trim() || undefined,
        apiKeyConfig: normalizeApiKeyConfig(config.apiKeyConfig),
      };
    });
}

function buildApiKeys(nodes: RFNode[]) {
  const apiKeys: Record<string, string> = {};

  for (const node of nodes) {
    const config = node.data?.config as Record<string, unknown> | undefined;
    const apiKeyConfig = normalizeApiKeyConfig(config?.apiKeyConfig);
    const apiKey = apiKeyConfig?.apiKey || String(config?.apiKey || "");
    if (!apiKey) continue;
    apiKeys[node.data?.type === "llm" ? "openai" : "api"] = apiKey;
  }

  return apiKeys;
}

function buildAgentConfig(
  nodes: RFNode[],
  edges: RFEdge[],
  agentType: string,
  options: GeneratorOptions,
) {
  const settings = options.settings || {};
  const serializedNodes = nodes.map(normalizeNode);

  return {
    id: options.agentId || "",
    name: options.agentName || "NOVA Agent",
    type: agentType,
    settings: {
      instructions: settings.instructions || "",
      includeChatHistory: settings.includeChatHistory ?? true,
      model: settings.model || "gpt-5-mini",
      outputFormat: settings.outputFormat || "text",
    },
    nodes: serializedNodes,
    edges,
    customTools: (options.customTools || []).map((tool) => ({
      ...tool,
      apiKeyConfig: normalizeApiKeyConfig(tool.apiKeyConfig),
    })),
    generatedToolNodes: buildGeneratedToolNodes(serializedNodes),
  };
}

function buildJavaScriptRuntime(
  agentConfig: ReturnType<typeof buildAgentConfig>,
  apiKeys: Record<string, string>,
  isTs: boolean,
) {
  return `/* eslint-disable no-console */
/**
 * Auto-generated by NOVA Agent Builder
 * Agent Name: ${escapeTemplate(agentConfig.name)}
 * Agent ID: ${escapeTemplate(agentConfig.id || "unknown")}
 * Agent Type: ${escapeTemplate(agentConfig.type)}
 */
const API_KEYS = ${JSON.stringify(apiKeys, null, 2)};
const BASE_URL = process.env.NOVA_AGENT_BASE_URL || process.env.NEXT_PUBLIC_APP_URL || process.env.NEXT_PUBLIC_BASE_URL || (typeof window !== "undefined" ? window.location.origin : process.env.RENDER_EXTERNAL_URL ? 'https://' + process.env.RENDER_EXTERNAL_URL : "http://localhost:3000");
const AGENT = ${JSON.stringify(agentConfig, null, 2)};
const text = (value) => String(value || "").trim();
const slug = (value) => text(value).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
const words = (value) => text(value).toLowerCase().split(/[^a-z0-9/_.:-]+/).filter(Boolean);
const escapeRegExp = (value) => String(value).replace(/[.*+?^\\\${}()|[\\]\\\\]/g, "\\\\$&");
const resolveUrl = (value) => /^https?:\\/\\//i.test(text(value)) ? text(value) : new URL(text(value).startsWith("/") ? text(value) : \`/\${text(value)}\`, BASE_URL).toString();
const detectKind = (tool) => {
  const haystack = [tool.name, tool.description, tool.id, tool.apiUrl].join(" ").toLowerCase();
  if (/exchangerate|currency|fx|forex/.test(haystack)) return "currency";
  if (/openweathermap|weather|forecast|temperature/.test(haystack)) return "weather";
  if (/worldtimeapi|timezone|datetime|current time/.test(haystack)) return "time";
  if (/restcountries|country|capital|population/.test(haystack)) return "country";
  if (/coingecko|crypto|bitcoin|ethereum|dogecoin|solana/.test(haystack)) return "crypto";
  if (/ipapi|geoip|geolocation|ip address/.test(haystack)) return "ip";
  if (/official-joke-api|joke|punchline/.test(haystack)) return "joke";
  if (/numbersapi|number fact|fun fact/.test(haystack)) return "number";
  return "generic";
};
const KIND_ALIASES = {
  currency: ["currency", "converter", "convert", "exchange", "rate", "forex"],
  weather: ["weather", "forecast", "temperature", "climate"],
  time: ["time", "timezone", "clock", "datetime"],
  country: ["country", "capital", "population", "nation"],
  crypto: ["crypto", "coin", "bitcoin", "ethereum", "dogecoin", "solana"],
  ip: ["ip", "geo", "geolocation", "location"],
  joke: ["joke", "funny", "laugh"],
  number: ["number", "fact", "math", "datefact"],
  generic: ["tool", "api", "agent"],
};
const runtimeTools = (() => {
  const merged = [...(AGENT.customTools || []), ...(AGENT.generatedToolNodes || [])];
  const seen = new Set();
  return merged.flatMap((tool) => {
    const apiUrl = text(tool.apiUrl);
    if (!apiUrl) return [];
    const key = [tool.id, tool.name, apiUrl, tool.method || "GET"].join("|");
    if (seen.has(key)) return [];
    seen.add(key);
    return [{ id: tool.id || slug(tool.name || apiUrl), name: text(tool.name) || "API Agent", description: text(tool.description), apiUrl, method: text(tool.method || "GET").toUpperCase(), apiKey: text(tool.apiKey), apiKeyConfig: tool.apiKeyConfig || null }];
  });
})();
const singleTool = runtimeTools.length === 1 ? runtimeTools[0] : null;
const authFor = (tool) => {
  const direct = tool.apiKeyConfig && tool.apiKeyConfig.useApiKey && text(tool.apiKeyConfig.apiKey)
    ? { useApiKey: true, apiKey: text(tool.apiKeyConfig.apiKey), authType: text(tool.apiKeyConfig.authType || "bearer"), customHeaderName: text(tool.apiKeyConfig.customHeaderName || "") }
    : null;
  if (direct) return direct;
  const apiKey = text(tool.apiKey || API_KEYS.api || process.env.API_KEY || "");
  return apiKey ? { useApiKey: true, apiKey, authType: "bearer", customHeaderName: "" } : null;
};
const buildHeaders = (tool, extra = {}) => {
  const headers = { Accept: "application/json, text/plain;q=0.9, */*;q=0.8", ...extra };
  const auth = authFor(tool);
  if (!auth?.useApiKey || !auth.apiKey || auth.authType === "query") return headers;
  if (auth.authType === "api-key") headers["X-API-Key"] = auth.apiKey;
  else if (auth.authType === "custom") headers[auth.customHeaderName || "Authorization"] = auth.apiKey;
  else headers.Authorization = \`Bearer \${auth.apiKey}\`;
  return headers;
};
const aliasesFor = (tool) => Array.from(new Set([tool.id, tool.name, tool.description, slug(tool.id), slug(tool.name), ...(KIND_ALIASES[detectKind(tool)] || [])].flatMap(words))).filter(Boolean);
const stripPrefix = (prompt, aliases) => text(prompt).replace(new RegExp(\`^\\\\s*(?:\${aliases.map(escapeRegExp).join("|")})\\\\b[:\\\\s-]*\`, "i"), "").trim();
const parseAmount = (prompt, fallback = 1) => Number((text(prompt).match(/-?\\d+(?:\\.\\d+)?/) || [String(fallback)])[0]);
const parseCodes = (prompt) => text(prompt).toUpperCase().match(/\\b[A-Z]{3}\\b/g) || [];
const fetchData = async (tool, request) => {
  const response = await fetch(request.url, { method: request.method, headers: request.headers, body: request.body ? JSON.stringify(request.body) : undefined });
  const contentType = response.headers.get("content-type") || "";
  const data = contentType.includes("json") ? await response.json() : await response.text();
  if (!response.ok) throw new Error(typeof data === "string" ? data : data?.error || data?.message || \`Request failed with status \${response.status}\`);
  return { data, request, tool };
};
const runCurrencyAgent = async (tool, prompt) => {
  const codes = parseCodes(prompt);
  const fallbackBase = (tool.apiUrl.match(/\\/latest\\/([A-Za-z]{3})/i)?.[1] || "USD").toUpperCase();
  const from = codes.length >= 2 ? codes[0] : fallbackBase;
  const to = codes.length >= 2 ? codes[1] : (codes[0] || (from === "USD" ? "INR" : "USD"));
  const amount = parseAmount(prompt, 1);
  const url = resolveUrl(tool.apiUrl).replace(/\\/latest\\/[A-Za-z]{3}\\/?(?:\\?.*)?$/i, \`/latest/\${from}\`);
  const result = await fetchData(tool, { method: "GET", url, headers: buildHeaders(tool), meta: { amount, from, to } });
  const rate = result.data?.rates?.[to];
  const converted = typeof result.data?.convertedAmount === "number" ? result.data.convertedAmount : typeof rate === "number" ? Number((amount * rate).toFixed(2)) : null;
  return { agent: tool.name, reply: converted == null ? JSON.stringify(result.data, null, 2) : \`\${amount} \${from} = \${converted} \${to}\\nLive rate: \${rate ?? "unknown"}\`, toolResult: result };
};
const runWeatherAgent = async (tool, prompt, aliases) => {
  const city = stripPrefix(prompt, aliases) || "Delhi";
  const auth = authFor(tool);
  const url = new URL(resolveUrl(tool.apiUrl));
  url.searchParams.set("q", city);
  url.searchParams.set("units", url.searchParams.get("units") || "metric");
  if (auth?.authType === "query" && auth.apiKey && !url.searchParams.has("appid")) url.searchParams.set("appid", auth.apiKey);
  const result = await fetchData(tool, { method: "GET", url: url.toString(), headers: buildHeaders(tool), meta: { city } });
  return { agent: tool.name, reply: [\`Weather for \${result.data?.name || city}\`, \`Temperature: \${result.data?.main?.temp ?? result.data?.temperature ?? "unknown"}\`, \`Feels like: \${result.data?.main?.feels_like ?? result.data?.feelsLike ?? "unknown"}\`, \`Condition: \${result.data?.weather?.[0]?.description || result.data?.description || "unknown"}\`].join("\\n"), toolResult: result };
};
const runTimeAgent = async (tool, prompt, aliases) => {
  const timezone = (stripPrefix(prompt, aliases) || "Asia/Kolkata").replace(/\\s+/g, "_");
  const url = resolveUrl(tool.apiUrl).replace(/\\/[A-Za-z_]+(?:\\/[A-Za-z_]+)*\\/?$/i, "") + \`/\${timezone}\`;
  const result = await fetchData(tool, { method: "GET", url, headers: buildHeaders(tool), meta: { timezone } });
  return { agent: tool.name, reply: [\`Timezone: \${result.data?.timezone || timezone}\`, \`Datetime: \${result.data?.datetime || result.data?.currentDateTime || result.data?.utc_datetime || "unknown"}\`, \`UTC Offset: \${result.data?.utc_offset || result.data?.utcOffset || "unknown"}\`].join("\\n"), toolResult: result };
};
const runCountryAgent = async (tool, prompt, aliases) => {
  const country = stripPrefix(prompt, aliases) || "india";
  const url = resolveUrl(tool.apiUrl).replace(/\\/[^/]+\\/?$/i, "") + \`/\${encodeURIComponent(country)}\`;
  const result = await fetchData(tool, { method: "GET", url, headers: buildHeaders(tool), meta: { country } });
  const item = Array.isArray(result.data) ? result.data[0] : result.data;
  return { agent: tool.name, reply: [\`Country: \${item?.name?.common || item?.name || country}\`, \`Capital: \${Array.isArray(item?.capital) ? item.capital.join(", ") : item?.capital || "unknown"}\`, \`Population: \${item?.population?.toLocaleString?.() || item?.population || "unknown"}\`].join("\\n"), toolResult: result };
};
const runCryptoAgent = async (tool, prompt, aliases) => {
  const parts = (stripPrefix(prompt, aliases) || "bitcoin usd,inr").split(/\\s+/).filter(Boolean);
  const coin = (parts[0] || "bitcoin").toLowerCase();
  const currencies = (parts[1] || "usd,inr").toLowerCase();
  const url = new URL(resolveUrl(tool.apiUrl));
  url.searchParams.set("ids", coin);
  url.searchParams.set("vs_currencies", currencies);
  const result = await fetchData(tool, { method: "GET", url: url.toString(), headers: buildHeaders(tool), meta: { coin, currencies } });
  const prices = result.data?.[coin] || {};
  return { agent: tool.name, reply: \`Crypto: \${coin}\\n\${Object.entries(prices).map(([k, v]) => \`\${String(k).toUpperCase()}: \${v}\`).join("\\n") || "No price data returned"}\`, toolResult: result };
};
const runIpAgent = async (tool, prompt, aliases) => {
  const ip = stripPrefix(prompt, aliases) || "json";
  const rawUrl = resolveUrl(tool.apiUrl);
  const url = /\\/json\\/?$/i.test(rawUrl) ? (ip === "json" ? "https://ipapi.co/json/" : \`https://ipapi.co/\${ip}/json/\`) : rawUrl;
  const result = await fetchData(tool, { method: "GET", url, headers: buildHeaders(tool), meta: { ip } });
  return { agent: tool.name, reply: [\`IP: \${result.data?.ip || (ip === "json" ? "auto-detect" : ip)}\`, \`City: \${result.data?.city || "unknown"}\`, \`Country: \${result.data?.country_name || result.data?.country || "unknown"}\`, \`Org: \${result.data?.org || result.data?.asn || "unknown"}\`].join("\\n"), toolResult: result };
};
const runJokeAgent = async (tool) => {
  const result = await fetchData(tool, { method: "GET", url: resolveUrl(tool.apiUrl), headers: buildHeaders(tool), meta: {} });
  return { agent: tool.name, reply: result.data?.setup && result.data?.punchline ? \`\${result.data.setup}\\n\${result.data.punchline}\` : JSON.stringify(result.data, null, 2), toolResult: result };
};
const runNumberAgent = async (tool, prompt, aliases) => {
  const number = (stripPrefix(prompt, aliases).match(/-?\\d+(?:\\.\\d+)?(?:\\/date)?/) || ["300"])[0];
  const url = resolveUrl(tool.apiUrl).replace(/\\/\\d+(?:\\/date)?\\/?$/i, "") + \`/\${number}\`;
  const result = await fetchData(tool, { method: "GET", url, headers: buildHeaders(tool), meta: { number } });
  return { agent: tool.name, reply: typeof result.data === "string" ? result.data : result.data?.text || result.data?.fact || JSON.stringify(result.data, null, 2), toolResult: result };
};
const runGenericAgent = async (tool, prompt, aliases) => {
  const query = stripPrefix(prompt, aliases) || prompt;
  const method = text(tool.method || "GET").toUpperCase();
  if (method === "GET") {
    const url = new URL(resolveUrl(tool.apiUrl));
    if (!url.searchParams.has("query")) url.searchParams.set("query", query);
    const result = await fetchData(tool, { method: "GET", url: url.toString(), headers: buildHeaders(tool), meta: { query } });
    return { agent: tool.name, reply: typeof result.data === "string" ? result.data : JSON.stringify(result.data, null, 2), toolResult: result };
  }
  const result = await fetchData(tool, { method, url: resolveUrl(tool.apiUrl), headers: buildHeaders(tool, { "Content-Type": "application/json" }), body: { prompt: query, query, input: query }, meta: { query } });
  return { agent: tool.name, reply: typeof result.data === "string" ? result.data : JSON.stringify(result.data, null, 2), toolResult: result };
};
const executeAgent = async (tool, prompt, aliases) => {
  const kind = detectKind(tool);
  if (kind === "currency") return { kind, ...(await runCurrencyAgent(tool, prompt)) };
  if (kind === "weather") return { kind, ...(await runWeatherAgent(tool, prompt, aliases)) };
  if (kind === "time") return { kind, ...(await runTimeAgent(tool, prompt, aliases)) };
  if (kind === "country") return { kind, ...(await runCountryAgent(tool, prompt, aliases)) };
  if (kind === "crypto") return { kind, ...(await runCryptoAgent(tool, prompt, aliases)) };
  if (kind === "ip") return { kind, ...(await runIpAgent(tool, prompt, aliases)) };
  if (kind === "joke") return { kind, ...(await runJokeAgent(tool)) };
  if (kind === "number") return { kind, ...(await runNumberAgent(tool, prompt, aliases)) };
  return { kind, ...(await runGenericAgent(tool, prompt, aliases)) };
};
const help = (activeTool) => singleTool
  ? [\`\${singleTool.name} Terminal Chat Active\`, \`Connected API: \${singleTool.apiUrl}\`, "Every message calls this API in real time.", "", 'Type "exit" to quit.'].join("\\n")
  : ["NOVA Terminal Chat Active", "Commands:", 'agents              Show all API agents', 'use <agent-name>    Switch active API agent', 'help                Show this help', 'exit                Quit', "", "Available agents:", ...runtimeTools.map((tool, index) => \`\${index + 1}. \${tool.name} (\${detectKind(tool)})\${activeTool?.id === tool.id ? " [active]" : ""}\`)].join("\\n");
const findTool = (prompt, forcedToolId) => {
  if (forcedToolId) return runtimeTools.find((tool) => tool.id === forcedToolId) || null;
  if (singleTool) return singleTool;
  const normalized = text(prompt).toLowerCase();
  const first = words(prompt)[0] || "";
  let best = null;
  for (const tool of runtimeTools) {
    const score = aliasesFor(tool).reduce((sum, alias) => sum + (normalized === alias ? 6 : first === alias ? 5 : normalized.includes(alias) ? 2 : 0), 0);
    if (!best || score > best.score) best = { tool, score };
  }
  return best && best.score > 0 ? best.tool : null;
};
async function runWorkflow(prompt, forcedToolId) {
  const tool = findTool(prompt, forcedToolId);
  if (!tool) return { prompt, toolMatch: null, reply: help(null) };
  const output = await executeAgent(tool, prompt, aliasesFor(tool));
  return { prompt, toolMatch: { toolId: tool.id, toolName: tool.name, kind: output.kind }, toolResult: output.toolResult, reply: output.reply, activeAgent: output.agent };
}
async function runAgent(prompt, options = {}) {
  const workflow = await runWorkflow(prompt, options.activeToolId);
  return { agent: workflow.activeAgent || workflow.toolMatch?.toolName || AGENT.name, mode: workflow.toolMatch ? "tool" : "help", workflow, reply: workflow.reply };
}
async function main() {
  const cliPrompt = process.argv.slice(2).join(" ").trim();
  if (cliPrompt) { const result = await runAgent(cliPrompt); console.log(\`[\${result.agent}]\\n\${result.reply}\`); return; }
  if (!process.stdin.isTTY) { console.log(help(null)); return; }
  const readline = (await import("readline/promises")).default;
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  let activeTool = singleTool;
  console.log(help(activeTool)); console.log("");
  while (true) {
    const prefix = activeTool ? activeTool.name : "NOVA";
    const userInput = text(await rl.question(\`\${prefix}> \`));
    if (!userInput) continue;
    const lower = userInput.toLowerCase();
    if (lower === "exit" || lower === "quit") break;
    if (lower === "help" || lower === "agents") { console.log(\`\\n\${help(activeTool)}\\n\`); continue; }
    if (lower.startsWith("use ")) {
      const wanted = text(userInput.slice(4)).toLowerCase();
      const nextTool = runtimeTools.find((tool) => tool.name.toLowerCase() === wanted || aliasesFor(tool).includes(wanted));
      if (!nextTool) { console.log('\\n[System]\\nAgent not found. Run "agents" to see available API agents.\\n'); continue; }
      activeTool = nextTool; console.log(\`\\n[System]\\nSwitched to \${nextTool.name}.\\n\`); continue;
    }
    try {
      const result = await runAgent(userInput, { activeToolId: activeTool?.id });
      console.log(\`\\n[\${result.agent}]\\n\${result.reply}\\n\`);
    } catch (error) {
      console.log(\`\\n[\${activeTool?.name || AGENT.name}]\\n\${error instanceof Error ? error.message : String(error)}\\n\`);
    }
  }
  rl.close();
}
if (typeof require !== "undefined" && require.main === module) {
  main().catch((error) => { console.error(error instanceof Error ? error.message : error); process.exit(1); });
}
${isTs ? "export { AGENT, runAgent, runWorkflow };" : "module.exports = { AGENT, runAgent, runWorkflow };"}\n`;
}

function buildPythonRuntime(
  agentConfig: ReturnType<typeof buildAgentConfig>,
  apiKeys: Record<string, string>,
) {
  return `#!/usr/bin/env python3
"""Auto-generated by NOVA Agent Builder."""
import json, os, re, sys, urllib.error, urllib.parse, urllib.request

API_KEYS = json.loads(r'''${escapePythonBlock(JSON.stringify(apiKeys, null, 2))}''')
AGENT = json.loads(r'''${escapePythonBlock(JSON.stringify(agentConfig, null, 2))}''')
BASE_URL = (
    os.environ.get("NOVA_AGENT_BASE_URL")
    or os.environ.get("NEXT_PUBLIC_APP_URL")
    or os.environ.get("NEXT_PUBLIC_BASE_URL")
    or ("https://" + os.environ.get("RENDER_EXTERNAL_URL"))
    or "http://localhost:3000"
)
ALIASES = {"currency":["currency","convert","rate","exchange"],"weather":["weather","forecast","temperature"],"ip":["ip","geo","geolocation","location"],"joke":["joke","funny","laugh"],"country":["country","capital"],"crypto":["crypto","coin","bitcoin","ethereum"],"time":["time","timezone","clock"],"number":["number","fact","math"],"generic":["tool","api"]}

def text(v): return str(v or "").strip()
def words(v): return [p for p in re.split(r"[^a-z0-9/_.:-]+", text(v).lower()) if p]
def slug(v): return re.sub(r"(^-+|-+$)", "", re.sub(r"[^a-z0-9]+", "-", text(v).lower()))
def resolve_url(url): return text(url) if re.match(r"^https?://", text(url), re.I) else (BASE_URL.rstrip("/") + (text(url) if text(url).startswith("/") else "/" + text(url)))
def pick_kind(tool):
    hay = " ".join([str(tool.get("name","")), str(tool.get("description","")), str(tool.get("id","")), str(tool.get("apiUrl",""))]).lower()
    if re.search(r"exchangerate|currency|fx", hay): return "currency"
    if re.search(r"weather|openweathermap|open-meteo", hay): return "weather"
    if re.search(r"ip|geoip|geolocation", hay): return "ip"
    if "joke" in hay: return "joke"
    if re.search(r"country|restcountries", hay): return "country"
    if re.search(r"crypto|bitcoin|coingecko|ethereum", hay): return "crypto"
    if re.search(r"timezone|worldtimeapi|current time", hay): return "time"
    if re.search(r"number|numbersapi|fact", hay): return "number"
    return "generic"
def normalize_auth(config):
    if not isinstance(config, dict): return None
    auth = config.get("authType") or config.get("headerType") or "bearer"
    return {"useApiKey": bool(config.get("useApiKey")), "apiKey": text(config.get("apiKey")), "authType": auth if auth in {"bearer","api-key","query","custom"} else "bearer", "customHeaderName": text(config.get("customHeaderName") or config.get("keyName") or "")}
def effective_auth(tool):
    direct = normalize_auth(tool.get("apiKeyConfig"))
    if direct and direct["useApiKey"] and direct["apiKey"]: return direct
    api_key = text(tool.get("apiKey") or API_KEYS.get("api") or os.environ.get("API_KEY") or "")
    return {"useApiKey": True, "apiKey": api_key, "authType": "bearer", "customHeaderName": ""} if api_key else None
def runtime_tools():
    merged = list(AGENT.get("customTools") or []) + list(AGENT.get("generatedToolNodes") or [])
    seen, items = set(), []
    for tool in merged:
        api_url = text(tool.get("apiUrl"))
        if not api_url: continue
        key = "|".join([str(tool.get("id")), str(tool.get("name")), api_url, str(tool.get("method") or "GET")])
        if key in seen: continue
        seen.add(key)
        items.append({"id": tool.get("id") or slug(tool.get("name") or api_url), "name": text(tool.get("name")) or "API Tool", "description": text(tool.get("description")), "apiUrl": api_url, "method": text(tool.get("method") or "GET").upper(), "paramsSchema": tool.get("paramsSchema") or {}, "apiKey": text(tool.get("apiKey")), "apiKeyConfig": effective_auth(tool)})
    return items
TOOLS = runtime_tools()
SINGLE = TOOLS[0] if len(TOOLS) == 1 else None
def aliases_for(tool): return list({*words(tool.get("id")), *words(tool.get("name")), *words(tool.get("description")), *ALIASES.get(pick_kind(tool), []), slug(tool.get("name")), slug(tool.get("id"))} - {""})
def parse_weather(prompt, aliases):
    pattern = r"^\\s*(?:" + "|".join(re.escape(alias) for alias in aliases) + r")\\b[:\\s-]*"
    value = re.sub(pattern, "", text(prompt), flags=re.I).strip()
    return value or "Delhi"
def values_for(prompt, tool, aliases):
    codes = re.findall(r"\\b[A-Z]{3}\\b", text(prompt).upper())
    weather = parse_weather(prompt, aliases)
    parts = weather.split()
    auth = effective_auth(tool) or {}
    return {"prompt": text(prompt), "query": text(prompt), "city": weather, "country": weather or "India", "timezone": weather.replace(" ", "_") or "Asia/Kolkata", "ip": weather or "8.8.8.8", "number": weather or "42", "coin": (parts[0] if parts else "bitcoin").lower(), "currencies": (parts[1] if len(parts) > 1 else "usd,inr").lower(), "amount": float((re.search(r"-?\\d+(?:\\.\\d+)?", text(prompt)) or ["1"])[0]), "from": codes[0] if len(codes) >= 2 else "USD", "to": codes[1] if len(codes) >= 2 else (codes[0] if codes else "INR"), "apiKey": text(auth.get("apiKey"))}
def value_for(key, values):
    key = text(key).lower()
    if "city" in key: return values["city"]
    if "country" in key: return values["country"]
    if "time" in key or "zone" in key: return values["timezone"]
    if key == "ip" or "geo" in key: return values["ip"]
    if "coin" in key or key == "ids": return values["coin"]
    if "curr" in key: return values["currencies"]
    if "from" in key or "base" in key: return values["from"]
    if "to" in key or "target" in key: return values["to"]
    if "amount" in key: return values["amount"]
    if "number" in key: return values["number"]
    return values["query"]
def build_request(tool, prompt, aliases):
    vals, kind = values_for(prompt, tool, aliases), pick_kind(tool)
    url = resolve_url(tool.get("apiUrl"))
    parsed = urllib.parse.urlparse(url)
    query = dict(urllib.parse.parse_qsl(parsed.query, keep_blank_values=True))
    schema = tool.get("paramsSchema") if isinstance(tool.get("paramsSchema"), dict) else {}
    if tool.get("method", "GET").upper() == "GET":
        if schema:
            for key in schema.keys(): query.setdefault(key, str(value_for(key, vals)))
        elif kind == "weather": query.setdefault("q", vals["city"])
        elif kind == "crypto": query.setdefault("ids", vals["coin"]); query.setdefault("vs_currencies", vals["currencies"])
        elif kind == "generic": query.setdefault("query", vals["query"])
    auth = effective_auth(tool)
    if auth and auth.get("useApiKey") and auth.get("apiKey") and auth.get("authType") == "query":
        query.setdefault("appid" if kind == "weather" else "key", auth["apiKey"])
    url = urllib.parse.urlunparse(parsed._replace(query=urllib.parse.urlencode(query)))
    headers = {"Accept": "application/json, text/plain;q=0.9, */*;q=0.8"}
    if auth and auth.get("useApiKey") and auth.get("apiKey") and auth.get("authType") != "query":
        if auth["authType"] == "api-key": headers["X-API-Key"] = auth["apiKey"]
        elif auth["authType"] == "custom": headers[auth.get("customHeaderName") or "Authorization"] = auth["apiKey"]
        else: headers["Authorization"] = "Bearer " + auth["apiKey"]
    body = {key: value_for(key, vals) for key in schema.keys()} if schema else vals
    return {"kind": kind, "method": text(tool.get("method") or "GET").upper(), "url": url, "headers": headers, "body": body, "meta": vals}
def execute(req):
    data = None if req["method"] == "GET" else json.dumps(req["body"]).encode("utf-8")
    if data is not None: req["headers"]["Content-Type"] = "application/json"
    request = urllib.request.Request(req["url"], data=data, headers=req["headers"], method=req["method"])
    with urllib.request.urlopen(request) as response:
        payload = response.read().decode("utf-8")
        content_type = response.headers.get("Content-Type", "")
        return json.loads(payload) if "json" in content_type.lower() else payload
def format_result(kind, data, meta):
    if kind == "currency" and isinstance(data, dict) and isinstance(data.get("convertedAmount"), (int, float)): return f"{data.get('amount')} {data.get('from')} = {data.get('convertedAmount')} {data.get('to')}"
    if kind == "currency" and isinstance(data, dict) and isinstance((data.get("rates") or {}).get(meta["to"]), (int, float)): return f"{meta['amount']} {meta['from']} = {meta['amount'] * data['rates'][meta['to']]:.2f} {meta['to']}"
    if kind == "weather" and isinstance(data, dict): return "\\n".join([f"Weather for {data.get('city') or meta['city']}", f"Temperature: {data.get('temperature') or ((data.get('main') or {}).get('temp')) or 'unknown'}", f"Condition: {data.get('description') or (((data.get('weather') or [{}])[0]).get('description')) or 'unknown'}"])
    if kind == "ip" and isinstance(data, dict): return "\\n".join([f"IP: {data.get('ip') or meta['ip']}", f"City: {data.get('city') or 'unknown'}", f"Country: {data.get('country_name') or data.get('country') or 'unknown'}"])
    if kind == "joke" and isinstance(data, dict) and data.get("setup"): return "\\n".join([p for p in [data.get("setup"), data.get("punchline")] if p])
    if kind == "country" and isinstance(data, list) and data: data = data[0]
    if kind == "country" and isinstance(data, dict): return "\\n".join([f"Country: {(data.get('name') or {}).get('common') if isinstance(data.get('name'), dict) else data.get('name') or meta['country']}", f"Capital: {', '.join(data.get('capital') or []) if isinstance(data.get('capital'), list) else data.get('capital') or 'unknown'}"])
    if kind == "time" and isinstance(data, dict): return "\\n".join([f"Timezone: {data.get('timezone') or meta['timezone']}", f"Datetime: {data.get('datetime') or data.get('currentDateTime') or data.get('utc_datetime') or 'unknown'}"])
    if kind == "crypto" and isinstance(data, dict) and data: 
        first_key = list(data.keys())[0]; return "Crypto: " + first_key + "\\n" + "\\n".join([f"{k.upper()}: {v}" for k, v in (data.get(first_key) or {}).items()])
    if kind == "number" and isinstance(data, dict): return data.get("text") or data.get("fact") or json.dumps(data, indent=2)
    return data if isinstance(data, str) else json.dumps(data, indent=2)
def find_tool(prompt, forced=None):
    if forced: 
        for tool in TOOLS:
            if tool["id"] == forced: return tool
    if SINGLE: return SINGLE
    normalized, first = text(prompt).lower(), (words(prompt)[0] if words(prompt) else "")
    best = None
    for tool in TOOLS:
        score = sum(6 if normalized == alias else 5 if first == alias else 2 if alias in normalized else 0 for alias in aliases_for(tool))
        if best is None or score > best[1]: best = (tool, score)
    return best[0] if best and best[1] > 0 else None
def help_text(active=None):
    if SINGLE: return "\\n".join([f"{SINGLE['name']} Terminal Chat Active", f"Connected API: {SINGLE['apiUrl']}", "Every message will use this API in real time.", "", 'Type "exit" to quit.'])
    return "\\n".join(["NOVA Terminal Chat Active","Commands:",'agents              Show all API agents','use <agent-name>    Switch active API agent','help                Show this help','exit                Quit',"","Available agents:",*[f"{i + 1}. {tool['name']} ({pick_kind(tool)}){' [active]' if active and active['id'] == tool['id'] else ''}" for i, tool in enumerate(TOOLS)]])
def run_agent(prompt, active_tool_id=None):
    tool = find_tool(prompt, active_tool_id)
    if not tool: return {"agent": AGENT.get("name", "NOVA Agent"), "reply": help_text()}
    req = build_request(tool, prompt, aliases_for(tool))
    data = execute(req)
    return {"agent": tool["name"], "reply": format_result(req["kind"], data, req["meta"])}
def find_by_name(name):
    wanted = text(name).lower()
    for tool in TOOLS:
        if tool["name"].lower() == wanted or wanted in aliases_for(tool): return tool
    return None
def main():
    cli = text(" ".join(sys.argv[1:]))
    if cli:
        result = run_agent(cli)
        print(f"[{result['agent']}]\\n{result['reply']}")
        return
    print(help_text(SINGLE))
    active = SINGLE
    while True:
        try: raw = text(input(f"{active['name'] if active else 'NOVA'}> "))
        except (EOFError, KeyboardInterrupt): print(""); break
        if not raw: continue
        lower = raw.lower()
        if lower in {"exit", "quit"}: break
        if lower in {"help", "agents"}: print("\\n" + help_text(active) + "\\n"); continue
        if lower.startswith("use "):
            nxt = find_by_name(raw[4:])
            if not nxt: print('\\n[System]\\nAgent not found. Run "agents" to see available API agents.\\n'); continue
            active = nxt; print(f"\\n[System]\\nSwitched to {nxt['name']}.\\n"); continue
        try:
            result = run_agent(raw, active["id"] if active else None)
            print(f"\\n[{result['agent']}]\\n{result['reply']}\\n")
        except Exception as exc:
            print(f"\\n[{active['name'] if active else AGENT.get('name', 'NOVA Agent')}]\\n{exc}\\n")
if __name__ == "__main__": main()
`;
}

export function generateAgentCode(
  nodes: RFNode[],
  edges: RFEdge[],
  agentType = "custom",
  options: GeneratorOptions = {},
): string {
  const settings = options.settings || {};
  const language = settings.codeLanguage || "javascript";
  const agentConfig = buildAgentConfig(nodes, edges, agentType, options);
  const apiKeys = buildApiKeys(nodes);

  if (language === "python") {
    return buildPythonRuntime(agentConfig, apiKeys);
  }

  return buildJavaScriptRuntime(agentConfig, apiKeys, language === "typescript");
}
