import type { CustomTool, RFEdge, RFNode } from "../types/agent-builder";

type GeneratorSettings = {
  instructions?: string;
  includeChatHistory?: boolean;
  model?: string;
  codeLanguage?: "javascript" | "typescript";
};

type GeneratorOptions = {
  agentId?: string;
  agentName?: string;
  customTools?: CustomTool[];
  settings?: GeneratorSettings;
};

function escapeTemplate(value: string) {
  return value.replace(/`/g, "\\`");
}

function normalizeNode(node: RFNode) {
  return {
    id: node.id,
    label: String(node.data?.label || node.id),
    type: String(node.data?.type || node.type || "default"),
    config: node.data?.config || {},
    position: node.position,
  };
}

export function generateAgentCode(
  nodes: RFNode[],
  edges: RFEdge[],
  agentType = "custom",
  options: GeneratorOptions = {}
): string {
  const agentName = options.agentName || "NOVA Agent";
  const customTools = options.customTools || [];
  const settings = options.settings || {};
  const language = settings.codeLanguage || "javascript";
  const isTs = language === "typescript";
  const serializedNodes = nodes.map(normalizeNode);

  // Collect API keys from nodes
  const apiKeys: Record<string, string> = {};
  nodes.forEach(node => {
    const config = node.data?.config;
    if (config?.apiKeyConfig?.useApiKey && config.apiKeyConfig.apiKey) {
      const key = config.apiKeyConfig.apiKey;
      const type = node.data?.type === 'llm' ? 'openai' : 'api';
      apiKeys[type] = key;
    }
  });

  return `${isTs ? "/* eslint-disable no-console */" : "#!/usr/bin/env node"}
/**
 * Auto-generated by NOVA Agent Builder
 * Agent Name: ${escapeTemplate(agentName)}
 * Agent ID: ${escapeTemplate(options.agentId || "unknown")}
 * Agent Type: ${escapeTemplate(agentType)}
 *
 * Usage:
 * 1. Run: node ${isTs ? "generated-agent.ts" : "generated-agent.js"} "your prompt"
 */

const API_KEYS = ${JSON.stringify(apiKeys, null, 2)};
const BASE_URL = process.env.NOVA_AGENT_BASE_URL || process.env.NEXT_PUBLIC_APP_URL || process.env.NEXT_PUBLIC_BASE_URL || (typeof window !== "undefined" ? window.location.origin : process.env.RENDER_EXTERNAL_URL ? 'https://' + process.env.RENDER_EXTERNAL_URL : "http://localhost:3000");

const AGENT = ${JSON.stringify(
    {
      id: options.agentId || "",
      name: agentName,
      type: agentType,
      settings: {
        instructions: settings.instructions || "",
        includeChatHistory: settings.includeChatHistory ?? true,
        model: settings.model || "gpt-4o-mini",
      },
      nodes: serializedNodes,
      edges,
      customTools,
    },
    null,
    2
  )};

${isTs ? "type WorkflowState = Record<string, unknown>;" : ""}

function slugify(value${isTs ? ": string" : ""}) {
  return String(value || "step")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

function resolveToolUrl(url${isTs ? ": string" : ""}) {
  if (!url) return url;
  if (/^https?:\\/\\//i.test(url)) {
    return url;
  }
  return new URL(url.startsWith("/") ? url : \`/\${url}\`, BASE_URL).toString();
}

function pickBestUrl(rawValue${isTs ? ": string" : ""}) {
  if (!rawValue) return rawValue;

  const candidates = String(rawValue)
    .split(/\\s+/)
    .map((item) => item.trim())
    .filter(Boolean);

  if (candidates.length <= 1) {
    return rawValue;
  }

  const preferred = candidates.find(
    (item) =>
      /^https?:\\/\\//i.test(item) &&
      !/\\/docs(\\/|$)/i.test(item) &&
      !/\\/en\\/docs(\\/|$)/i.test(item)
  );

  return preferred || candidates[0];
}

async function callOpenAI(prompt${isTs ? ": string" : ""}, workflowState${isTs ? ": Record<string, unknown>" : ""}, apiKey${isTs ? "?: string" : ""}) {
  const apiKeyToUse = apiKey || API_KEYS.openai || process.env.OPENAI_API_KEY;

  if (!apiKeyToUse) {
    return {
      mode: "offline",
      content:
        "OPENAI_API_KEY is not set. The workflow still ran, but the model response is in offline mode.",
    };
  }

  const systemPrompt = [
    \`You are \${AGENT.name}.\`,
    AGENT.settings.instructions || "Follow the configured workflow and tools exactly.",
    "Workflow nodes:",
    JSON.stringify(AGENT.nodes, null, 2),
    "Workflow edges:",
    JSON.stringify(AGENT.edges, null, 2),
    "Custom tools:",
    JSON.stringify(AGENT.customTools, null, 2),
    "Current workflow state:",
    JSON.stringify(workflowState, null, 2),
  ].join("\\n\\n");

const response = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: \`Bearer \${apiKeyToUse}\`,
    },
    body: JSON.stringify({
      model: AGENT.settings.model || "gpt-4o-mini",
      input: [
        {
          role: "system",
          content: [{ type: "input_text", text: systemPrompt }],
        },
        {
          role: "user",
          content: [{ type: "input_text", text: prompt }],
        },
      ],
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: prompt }
      ],
      temperature: 0.7,
      max_tokens: 2000,
    }),
  });

  const payload = await response.json();
  if (!response.ok) {
    throw new Error(payload?.error?.message || "OpenAI request failed");
  }

  const fallback =
    payload?.output_text ||
    payload?.output?.map?.((item${isTs ? ": any" : ""}) => item?.content?.map?.((part${isTs ? ": any" : ""}) => part?.text).join("")).join("\\n") ||
    "";

  return {
    mode: "openai",
    content: fallback,
    raw: payload,
  };
}

async function executeHttpTool(tool${isTs ? ": any" : ""}, prompt${isTs ? ": string" : ""}, state${isTs ? ": Record<string, unknown>" : ""}, apiKeyConfig${isTs ? "?: any" : ""}) {
  const normalizedApiUrl = pickBestUrl(tool.apiUrl || "");

  if (!normalizedApiUrl) {
    return {
      ok: false,
      skipped: true,
      reason: "Missing apiUrl",
    };
  }

  const method = (tool.method || "GET").toUpperCase();
  const shouldSendBody = ["POST", "PUT", "PATCH", "DELETE"].includes(method);
  const headers${isTs ? ": Record<string, string>" : ""} = {
  "Content-Type": "application/json",
};

// Add API key headers if configured
if (apiKeyConfig?.useApiKey && apiKeyConfig.apiKey) {
  const headerName = 
    apiKeyConfig.headerType === 'custom'
      ? apiKeyConfig.keyName || 'Authorization'
      : apiKeyConfig.headerType === 'api-key'
      ? 'X-API-Key'
      : 'Authorization';

    const headerValue = 
      apiKeyConfig.headerType === 'bearer'
        ? \`Bearer \${apiKeyConfig.apiKey}\`
        : apiKeyConfig.apiKey;

  headers[headerName] = headerValue;
}

  const response = await fetch(resolveToolUrl(normalizedApiUrl), {
    method,
    headers,
    body: shouldSendBody
      ? JSON.stringify({
          prompt,
          state,
          city: prompt,
          location: prompt,
          currency: prompt,
          base: prompt,
          params: tool.paramsSchema || {},
        })
      : undefined,
  });

  const contentType = response.headers.get("content-type") || "";
  const data = contentType.includes("application/json")
    ? await response.json()
    : await response.text();

  return {
    ok: response.ok,
    status: response.status,
    data,
  };
}

async function runWorkflow(prompt${isTs ? ": string" : ""})${isTs ? ": Promise<WorkflowState>" : ""} {
  const state${isTs ? ": WorkflowState" : ""} = {
    prompt,
    visitedNodes: [],
  };

  for (const node of AGENT.nodes) {
    const key = slugify(node.label || node.id);
    const type = node.type;
    const config = node.config || {};
    state.visitedNodes.push(node.id);

    if (type === "api") {
      state[key] = await executeHttpTool(
        {
          apiUrl: config.apiUrl,
          method: config.method || "GET",
          paramsSchema: config.paramsSchema || {},
        },
        prompt,
        state,
        config.apiKeyConfig
      );
      continue;
    }

    if (type === "custom") {
      const tool = AGENT.customTools.find((item${isTs ? ": any" : ""}) => item.id === config.toolId);
      state[key] = tool
        ? await executeHttpTool(tool, prompt, state, config.apiKeyConfig)
        : { ok: false, skipped: true, reason: "Custom tool not found" };
      continue;
    }

    if (type === "if") {
      state[key] = {
        branch: config.condition || "manual-condition",
        evaluated: true,
      };
      continue;
    }

    if (type === "while") {
      state[key] = {
        loop: config.condition || "manual-loop",
        maxIterations: config.maxIterations || 3,
      };
      continue;
    }

    if (type === "llm") {
      // Execute an LLM call as part of the workflow step
      const promptForLLM = config.prompt || prompt;
      const llmResp = await callOpenAI(promptForLLM, state, config.apiKeyConfig?.apiKey);
      state[key] = {
        type,
        label: node.label,
        config,
        response: llmResp,
      };
      continue;
    }

    state[key] = {
      type,
      label: node.label,
      config,
    };
  }

  return state;
}

function summarizeWorkflowReply(workflow${isTs ? ": Record<string, unknown>" : ""}) {
  for (const [key, value] of Object.entries(workflow)) {
    if (["prompt", "visitedNodes", "chatHistory"].includes(key)) {
      continue;
    }

    const typedValue = value${isTs ? " as any" : ""};
    if (typedValue?.data?.text) {
      return typedValue.data.text;
    }
    if (typedValue?.data && typeof typedValue.data === "object") {
      return JSON.stringify(typedValue.data, null, 2);
    }
  }

  return null;
}

async function runAgent(prompt${isTs ? ": string" : ""}, chatHistory${isTs ? ": Array<{ role: string; content: string }> = []" : " = []"}) {
  const workflow = await runWorkflow(prompt);
  if (AGENT.settings.includeChatHistory) {
    workflow.chatHistory = chatHistory;
  }

  const completion = await callOpenAI(prompt, workflow);
  const workflowReply = summarizeWorkflowReply(workflow);
  return {
    agent: AGENT.name,
    mode: completion.mode,
    workflow,
      reply: completion.mode === "offline" && workflowReply ? workflowReply : completion.content,
  };
}

async function main() {
  let prompt = process.argv.slice(2).join(" ").trim();

  if (!prompt) {
    if (!process.stdin.isTTY) {
      console.log("This generated file supports interactive terminal chat, but the current runner is non-interactive.");
      console.log("Run it in a real terminal instead:");
      console.log(\`  set NOVA_AGENT_BASE_URL=\${BASE_URL}\`);
      console.log("  node generated-agent.js");
      console.log('Or run one-shot mode: node generated-agent.js "INR"');
      return;
    }

    const readline = (await import("readline/promises")).default;
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    const chatHistory${isTs ? ": Array<{ role: string; content: string }>" : ""} = [];

    console.log(\`Starting \${AGENT.name} terminal chat.\`);
    console.log("Type a city or 'city, country' for live location data.");
    console.log("Type 'exit' to quit.\\n");

    while (true) {
      const userInput = (await rl.question("> ")).trim();
      if (!userInput) {
        continue;
      }
      if (["exit", "quit"].includes(userInput.toLowerCase())) {
        break;
      }

      chatHistory.push({ role: "user", content: userInput });
      const result = await runAgent(userInput, chatHistory);
      const reply =
        typeof result.reply === "string"
          ? result.reply
          : JSON.stringify(result.reply, null, 2);

      console.log("\\n" + reply + "\\n");
      chatHistory.push({ role: "assistant", content: reply });
    }

    rl.close();
    return;
  }

  const result = await runAgent(prompt);
  console.log(
    typeof result.reply === "string"
      ? result.reply
      : JSON.stringify(result.reply, null, 2)
  );
}

if (typeof require !== "undefined" && require.main === module) {
  main().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}

${isTs ? "export { AGENT, runAgent, runWorkflow };" : "module.exports = { AGENT, runAgent, runWorkflow };"}
`;
}
